import Property from '../comps/Property'
import Head from 'next/head'
import Image from 'next/image'
import { FormControl,InputLabel,Select,MenuItem } from '@mui/material'
import { useState } from 'react'
import { Button } from "@mui/material";
import MyImage from '../public/not-found.jpg'
import {FaSearch} from 'react-icons/fa'
import { RotateLoader } from 'react-spinners'

const Search = () => {

    const [purpose,setPurpose]=useState('for-sale')
    const [sort,setSort] = useState('price-asc')
    const [priceMin,setPriceMin] = useState(5000)
    const [priceMax,setPriceMax] = useState(7000000)
    const [roomsMin,setRoomsMin] =useState(1)
    const [propertyType,setPropertyType] = useState(4)
    const [bathsMin,setBathsMin] = useState(1)
    const [furnishingStatus,setFurnishingStatus] = useState('unfurnished')
    const [property,setProperty] = useState(null)
    const [loader,setLoader] = useState(false)


    function handleClick(){
        setLoader(true)
        const options = {
            method: 'GET',
            headers: {
                'X-RapidAPI-Key': process.env.NEXT_PUBLIC_API_KEY,
                'X-RapidAPI-Host': 'bayut.p.rapidapi.com'
            }
        };
        
        fetch(`https://bayut.p.rapidapi.com/properties/list?locationExternalIDs=5002%2C6020&roomsMin=${roomsMin}&categoryExternalID=${propertyType}&bathsMin=${bathsMin}&furnishingStatus=${furnishingStatus}&priceMin=${priceMin}&priceMax=${priceMax}&sort=${sort}&purpose=${purpose}`, options)
            .then(response => response.json())
            .then(data => {
                setLoader(false)
                setProperty(data?.hits)
                setTimeout(()=>document.getElementById("results").scrollIntoView(true),1000)
            })
            .catch(err => console.error(err));
    }

    return ( 
        <div>
      <Head>
        <title>Real Estate | Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="search-filters">
            <h2>Search Filters:</h2>
            <div className="select-input">
                <FormControl sx={{width:'250px',margin:1}}>
                    <InputLabel id="demo-simple-select-label">Purpose</InputLabel>
                    <Select
                        label="Purpose"
                        onChange={(e)=>setPurpose(e.target.value)}
                        defaultValue="for-sale"
                    >
                        <MenuItem value="for-sale">For Sale</MenuItem>
                        <MenuItem value="for-rent">For Rent</MenuItem>
                    </Select>
                </FormControl>
                <FormControl sx={{width:'250px',margin:1}}>
                    <InputLabel id="demo-simple-select-label">Sort</InputLabel>
                    <Select
                        label="Sort"
                        onChange={(e)=>setSort(e.target.value)}
                        defaultValue="price-asc"
                    >
                        <MenuItem value="price-desc">Price Desc</MenuItem>
                        <MenuItem value="price-asc">Price Asc</MenuItem>
                        <MenuItem value="city-level-score">City Level Score</MenuItem>
                        <MenuItem value="date-desc">Date Desc</MenuItem>
                        <MenuItem value="verified-score">Verified Score</MenuItem>
                    </Select>
                </FormControl>
                    {purpose === 'for-rent' &&
                        <FormControl sx={{width:'250px',margin:1}}>
                        <InputLabel id="demo-simple-select-label">Price Min</InputLabel>
                        <Select
                        label="Price Min"
                        onChange={(e)=>setPriceMin(e.target.value)}
                        defaultValue="5000"
                    >
                        <MenuItem value="5000">5K</MenuItem>
                        <MenuItem value="10000">10K</MenuItem>
                        <MenuItem value="20000">20K</MenuItem>
                        <MenuItem value="30000">30K</MenuItem>
                        <MenuItem value="50000">50K</MenuItem>
                    </Select></FormControl> }
                   { purpose === 'for-sale' &&
                    <FormControl sx={{width:'250px',margin:1}}>
                    <InputLabel id="demo-simple-select-label">Price Min</InputLabel>
                    <Select
                    label="Price Min"
                    onChange={(e)=>setPriceMin(e.target.value)}
                    defaultValue="100000"
                >
                    <MenuItem value="100000">100K</MenuItem>
                    <MenuItem value="250000">250K</MenuItem>
                    <MenuItem value="500000">500K</MenuItem>
                    <MenuItem value="1000000">1M</MenuItem>
                </Select></FormControl>}
                    
                {purpose === 'for-sale' &&
                <FormControl sx={{width:'250px',margin:1}}>
                    <InputLabel id="demo-simple-select-label">Price Max</InputLabel>
                    <Select
                        label="Price Max"
                        onChange={(e)=>setPriceMax(e.target.value)}
                        defaultValue="7000000"
                    >
                        <MenuItem value="1000000">1M</MenuItem>
                        <MenuItem value="2500000">2.5M</MenuItem>
                        <MenuItem value="5000000">5M</MenuItem>
                        <MenuItem value="7000000">7M</MenuItem>
                    </Select>
                </FormControl>}
                {purpose === 'for-rent' &&
                <FormControl sx={{width:'250px',margin:1}}>
                    <InputLabel id="demo-simple-select-label">Price Max</InputLabel>
                    <Select
                        label="Price Max"
                        onChange={(e)=>setPriceMax(e.target.value)}
                        defaultValue="500000"
                    >
                        <MenuItem value="50000">50K</MenuItem>
                        <MenuItem value="100000">100K</MenuItem>
                        <MenuItem value="500000">500K</MenuItem>
                        <MenuItem value="1000000">1M</MenuItem>
                    </Select>
                </FormControl>}
                <FormControl sx={{width:'250px',margin:1}}>
                    <InputLabel id="demo-simple-select-label">Rooms Min</InputLabel>
                    <Select
                        label="Rooms Min"
                        onChange={(e)=>setRoomsMin(e.target.value)}
                        defaultValue="1"
                    >
                        <MenuItem value="1">1</MenuItem>
                        <MenuItem value="2">2</MenuItem>
                        <MenuItem value="3">3</MenuItem>
                        <MenuItem value="4">4</MenuItem>
                        <MenuItem value="5">5</MenuItem>
                        <MenuItem value="6">6</MenuItem>
                    </Select>
                </FormControl>
                <FormControl sx={{width:'250px',margin:1}}>
                    <InputLabel id="demo-simple-select-label">Baths Min</InputLabel>
                    <Select
                        label="Baths Min"
                        onChange={(e)=>setBathsMin(e.target.value)}
                        defaultValue="1"
                    >
                        <MenuItem value="1">1</MenuItem>
                        <MenuItem value="2">2</MenuItem>
                        <MenuItem value="3">3</MenuItem>
                        <MenuItem value="4">4</MenuItem>
                        <MenuItem value="5">5</MenuItem>
                        <MenuItem value="6">6</MenuItem>
                    </Select>
                </FormControl>
                <FormControl sx={{width:'250px',margin:1}}>
                    <InputLabel id="demo-simple-select-label">Property Type</InputLabel>
                    <Select
                        label="Property Type"
                        onChange={(e)=>setPropertyType(e.target.value)}
                        defaultValue="4"
                    >
                        <MenuItem value="4">Apartment</MenuItem>
                        <MenuItem value="16">Townhouse</MenuItem>
                        <MenuItem value="3">Villa</MenuItem>
                        <MenuItem value="18">Penthouse</MenuItem>
                    </Select>
                </FormControl>
                <FormControl sx={{width:'250px',margin:1}}>
                    <InputLabel id="demo-simple-select-label">Furnishing Status</InputLabel>
                    <Select
                        label="Furnishing Status"
                        onChange={(e)=>setFurnishingStatus(e.target.value)}
                        defaultValue="unfurnished"
                    >
                        <MenuItem value="furnished">Furnished</MenuItem>
                        <MenuItem value="unfurnished">Unfurnished</MenuItem>
                    </Select>
                </FormControl>
            </div>
            <div>
                <Button variant="outlined" color="info" onClick={handleClick} href='#loader'>Search</Button>
            </div>
        </div>
        <div id="results">
        {loader ?
        <div className="loader">
            <RotateLoader
                color='#000'
                size={20}
                aria-label="Loading Spinner"
                data-testid="loader"
            />
        </div>:
        property === null ?
        <div className="search-start">
            <h1><FaSearch/>&nbsp;Search your dream property!</h1>
        </div>
         :
        property !== [] ?
        <div>
            <div className="rent-heading">
                <h1>Search Results</h1>
                <p>Hope you like them</p>
            </div>
            <div className="card-container">{property.map((property)=>{
            return <Property property={property} key={property.id}/> 
            })}</div>
        </div> 
        :
         <div className="no-result">
            <Image src={MyImage} width={500} height={500}/>
            <div>No Results available!</div>
        </div>
        }</div>
        
      </div>
    </div>
     );
}
 
export default Search;
