import {FaBed,FaBath} from 'react-icons/fa';
import {BsGridFill} from 'react-icons/bs';
import {GoVerified} from 'react-icons/go';
import millify from 'millify';
import { baseUrl, fetchApi } from '../../utils/fetchApi'
import Carousel from 'react-material-ui-carousel'
import Head from 'next/head'
import Image from 'next/image';
import Table from '@mui/material/Table';
import TableBody from '@mui/material/TableBody';
import TableCell from '@mui/material/TableCell';
import TableContainer from '@mui/material/TableContainer';
import TableHead from '@mui/material/TableHead';
import TableRow from '@mui/material/TableRow';
import Paper from '@mui/material/Paper';
import {ImPriceTag} from 'react-icons/im'
import {BiTargetLock,BiPulse} from 'react-icons/bi'
import {MdChair} from 'react-icons/md'
import {VscTypeHierarchySub} from 'react-icons/vsc'

const PropertyDetails = ({propertyDetails:{price,rentFrequency,rooms,title,baths,area,agency,isVerified,description,type,purpose,furnshingStatus,amenities,photos}}) => {

    console.log(amenities)
    return ( 
        <>
        <Head>
        <title>Real Estate | {title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <h2 style={{textAlign:'center'}}>{title}</h2>
        <Carousel sx={{width:'100%',marginBlock:"20px",textAlign:'center'}} animation='slide' duration='300' navButtonsAlwaysVisible='true'>
            {photos && photos.map((photo)=>(
                <img key={photo.url} src={photo.url} alt="" style={{width:'70%',height:'70vh',borderRadius:'10px'}}/>
            ))}
        </Carousel>
    <TableContainer>
      <Table sx={{ maxWidth: '600px',margin:'auto',backgroundColor:'rgba(227, 241, 253, 0.651)',borderRadius:'10px' }} aria-label="simple table">
        <TableBody>
            <TableRow >
                <TableCell sx={{fontWeight:'bold',fontSize:'1.1rem'}}><ImPriceTag/>&nbsp;Price</TableCell>
                <TableCell sx={{fontWeight:'bold',fontSize:'1.1rem'}} align="center">AED {millify(price)}</TableCell>
            </TableRow>
            <TableRow>
                <TableCell sx={{fontWeight:'bold',fontSize:'1.1rem'}}><FaBed/>&nbsp;Bedrooms</TableCell>
                <TableCell sx={{fontWeight:'bold',fontSize:'1.1rem'}} align="center">{rooms}</TableCell>
            </TableRow>
            <TableRow>
                <TableCell sx={{fontWeight:'bold',fontSize:'1.1rem'}}><FaBath/>&nbsp;Bathrooms</TableCell>
                <TableCell sx={{fontWeight:'bold',fontSize:'1.1rem'}} align="center">{baths}</TableCell>
            </TableRow>
            <TableRow>
                <TableCell sx={{fontWeight:'bold',fontSize:'1.1rem'}}><BsGridFill/>&nbsp;Area</TableCell>
                <TableCell sx={{fontWeight:'bold',fontSize:'1.1rem'}} align="center">{millify(area)}&nbsp;sqft</TableCell>
            </TableRow>
            <TableRow>
                <TableCell sx={{fontWeight:'bold',fontSize:'1.1rem'}}><VscTypeHierarchySub/>&nbsp;Type</TableCell>
                <TableCell sx={{fontWeight:'bold',fontSize:'1.1rem'}} align="center">{type}</TableCell>
            </TableRow>
            <TableRow>
                <TableCell sx={{fontWeight:'bold',fontSize:'1.1rem'}}><BiTargetLock/>&nbsp;Purpose</TableCell>
                <TableCell sx={{fontWeight:'bold',fontSize:'1.1rem'}} align="center">{purpose}</TableCell>
            </TableRow>
            <TableRow>
                <TableCell sx={{fontWeight:'bold',fontSize:'1.1rem'}}><MdChair/>&nbsp;Furnishing Status</TableCell>
                <TableCell sx={{fontWeight:'bold',fontSize:'1.1rem'}} align="center">{furnshingStatus ? furnshingStatus :'Unfurnished'}</TableCell>
            </TableRow>
            {rentFrequency && <TableRow>
                <TableCell sx={{fontWeight:'bold',fontSize:'1.1rem'}}><BiPulse/>&nbsp;Rent Frequency</TableCell>
                <TableCell sx={{fontWeight:'bold',fontSize:'1.1rem'}} align="center">{rentFrequency}</TableCell>
            </TableRow>}
            <TableRow>
                <TableCell sx={{fontWeight:'bold',fontSize:'1.1rem'}}><GoVerified/>&nbsp;Verified</TableCell>
                <TableCell sx={{fontWeight:'bold',fontSize:'1.1rem'}} align="center">{isVerified ? 'Yes' :'No'}</TableCell>
            </TableRow>
        </TableBody>
      </Table>
    </TableContainer>
    <div className='info-div'>
        <h4>Agency:</h4>
        <Image src={agency.logo.url} width={240} height={120}/>
        <h3>{agency.name}</h3>
    </div> 
        <div className='desc'>
            <h2>Description:</h2>
            <p>{description.replace(/<[^>]+>/g, '')}</p>
        </div>
        {amenities && <div className="amenities-div">
            <h2>Amenities:</h2>
            <div style={{display:'flex',flexWrap:'wrap'}}>{amenities.map((amenity)=>(
            <div className="amenity" key={amenity.text}>{amenity.text}</div>
        ))}</div>
        </div>}

        </>
     );
}
 
export default PropertyDetails;

export async function getServerSideProps({params:{id}}){
    const data = await fetchApi(`${baseUrl}/properties/detail?externalID=${id}`)
  
    return {
      props:{
        propertyDetails:data
      }
    }
  }